import { test, expect } from '@playwright/test'
async function login(page) {
 await page.goto('/')
 await page.getByLabel('用户名', {exact:true}).fill('demo_visitor')
 await page.getByLabel('密码', {exact:true}).fill('demo-password-123')
 await page.getByRole('button',{name:'登录',exact:true}).click()
 await expect(page.getByRole('textbox',{name:'描述你的需求'})).toBeEnabled()
}
const stats=async request=>(await request.get('/__fixture/state')).json()
const noOverflow=async page=>expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
let pageErrors
test.beforeEach(async({page,request})=>{pageErrors=[];page.on('pageerror',error=>pageErrors.push(error.message));await request.post('/__fixture/reset')})
test.afterEach(()=>{expect(pageErrors).toEqual([])})
test('login, useful quick prompts, search and desktop layout',async({page,request},info)=>{
 await page.goto('/');await page.screenshot({path:info.outputPath('login.png'),fullPage:true})
 await login(page);await noOverflow(page)
 await page.getByRole('button',{name:'01 了解导诊范围'}).click()
 await expect(page.locator('textarea')).toHaveValue('你能提供哪些就医准备帮助？')
 expect((await stats(request)).posts).toBe(0)
 await page.getByRole('searchbox',{name:'搜索已加载会话'}).fill('没有这个会话')
 await expect(page.getByText('已加载的会话中没有匹配项。')).toBeVisible()
 await page.getByRole('searchbox',{name:'搜索已加载会话'}).fill('')
 await page.screenshot({path:info.outputPath('desktop.png'),fullPage:true})
})
test('one send, source disclosure and HTML stays inert',async({page,request})=>{
 await login(page);await page.locator('textarea').fill('就诊需要准备什么？')
 await page.getByRole('button',{name:'发送消息',exact:true}).click()
 await expect(page.getByRole('button',{name:'发送消息',exact:true})).toBeDisabled()
 await expect(page.locator('.message-text').filter({hasText:'<img src=x'})).toBeVisible({timeout:12000})
 await expect(page.locator('.message-text img')).toHaveCount(0)
 await page.locator('.sources summary').click();await expect(page.getByText('演示资料：就诊前整理近期检查资料。')).toBeVisible()
 expect((await stats(request)).posts).toBe(1)
})
test('browser network interruption reconciles saved result without resending',async({page,context,request})=>{
 await login(page);await page.locator('textarea').fill('断网恢复测试')
 await page.getByRole('button',{name:'发送消息',exact:true}).click()
 await expect(page.getByText('正在整理就诊资料。',{exact:true})).toBeVisible()
 await context.setOffline(true)
 await expect(page.getByRole('alert')).toContainText('网络已断开')
 await expect(page.locator('textarea')).toBeDisabled()
 await expect(page.getByRole('button',{name:'选择此场次，生成草稿'})).toBeDisabled()
 await expect.poll(async()=>(await stats(request)).processing).toBe(false)
 await context.setOffline(false)
 await expect(page.locator('textarea')).toBeEnabled({timeout:15000})
 await expect(page.getByText('请整理近期检查资料。<img src=x onerror=alert(1)> 是测试文本。',{exact:true})).toBeVisible()
 expect((await stats(request)).posts).toBe(1)
 await page.reload();await expect(page.locator('textarea')).toBeEnabled()
 expect((await stats(request)).posts).toBe(1)
})
test('stop receiving keeps server work, refresh finds a single saved response',async({page,request})=>{
 await login(page);await page.locator('textarea').fill('停止后恢复测试')
 await page.getByRole('button',{name:'发送消息',exact:true}).click()
 await expect(page.getByText('正在整理就诊资料。',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'停止接收',exact:true}).click()
 await expect.poll(async()=>(await stats(request)).processing).toBe(false)
 await page.reload();await expect(page.locator('textarea')).toBeEnabled()
 await expect(page.locator('.bot-message')).toHaveCount(1)
 expect((await stats(request)).posts).toBe(1)
})
test('mobile booking requires final review; cancellation survives refresh',async({page,request},info)=>{
 await page.setViewportSize({width:390,height:844});await login(page);await noOverflow(page)
 await expect(page.getByRole('heading',{name:'今天，有什么可以帮你？'})).toBeInViewport()
 await page.screenshot({path:info.outputPath('mobile-chat.png'),fullPage:true})
 await page.getByRole('button',{name:'排班与预约',exact:true}).click()
 await page.getByRole('button',{name:'选择此场次，生成草稿'}).click()
 await expect(page.getByRole('button',{name:'确认创建演示预约',exact:true})).toBeEnabled()
 expect((await stats(request)).confirms).toBe(0)
 await page.getByRole('button',{name:'确认创建演示预约',exact:true}).click()
 await expect(page.getByRole('region',{name:'操作确认区'})).toBeVisible()
 expect((await stats(request)).confirms).toBe(0)
 await page.getByRole('button',{name:'核对无误，确认创建演示预约',exact:true}).click()
 await expect(page.getByRole('button',{name:'取消已确认的演示预约',exact:true})).toBeEnabled()
 await page.getByRole('button',{name:'取消已确认的演示预约',exact:true}).click()
 await page.getByRole('button',{name:'核对无误，取消已确认的演示预约',exact:true}).click()
 await expect.poll(async()=>(await stats(request)).cancels).toBe(1)
 await page.reload();await expect(page.locator('textarea')).toBeEnabled()
 await page.getByRole('button',{name:'排班与预约',exact:true}).click()
 await expect(page.getByText('查询时状态：预约已取消')).toBeVisible()
 await expect(page.getByRole('button',{name:'确认创建演示预约',exact:true})).toHaveCount(0)
 await noOverflow(page);await page.screenshot({path:info.outputPath('mobile-appointment.png'),fullPage:true})
 expect((await stats(request)).creates).toBe(1);expect((await stats(request)).confirms).toBe(1)
})
test('lab remains separate and displays actual retrieval response',async({page},info)=>{
 await login(page);await page.getByRole('button',{name:'AI 工程实验室',exact:true}).click()
 await page.getByRole('button',{name:'运行检索',exact:true}).click()
 await expect(page.getByText('采用 1 个片段')).toBeVisible()
 await noOverflow(page);await page.screenshot({path:info.outputPath('lab.png'),fullPage:true})
})

test('compact and tablet layouts do not overflow',async({page})=>{
 await login(page)
 for(const width of [320,768,1024]){
  await page.setViewportSize({width,height:900})
  await noOverflow(page)
 }
})
